{{ $architecture := or .architecture "arm64" }}
{{ $suite := or .suite "bullseye" }}

architecture: {{ $architecture }}

actions:
- action: overlay
  description: Copy root
  source: overlay/root
  destination: /root

- action: overlay
  description: Copy home
  source: overlay/home/open
  destination: /home/open
