# recipe.yaml

architecture: arm64

actions:
- action: recipe
  recipe: ../debos/ospack.yaml

- action: recipe
  recipe: ../debos/osvideopack.yaml
  variables:
    multi_cam_rkaiq: true

- action: recipe
  recipe: ./osmodelpack.yaml

- action: recipe
  recipe: ../debos/image.yaml
  variables:
    osinpack: osmodelpack
