# recipe.yaml

{{ $imgname := or .imgname "6tops" }}
{{ $buildnr := or .buildnr "b0" }}

architecture: arm64

actions:
- action: recipe
  recipe: ../debos/ospack.yaml
  variables:
    hostname: {{ $imgname }}

- action: recipe
  recipe: ../debos/osvideopack.yaml
  variables:
    multi_cam_rkaiq: true

- action: recipe
  recipe: ./modelpack.yaml

- action: recipe
  recipe: ../debos/image.yaml
  variables:
    osinpack: modelpack
    buildnr: {{ $buildnr }}
