# recipe.yaml

architecture: amd64

actions:
- action: run
  description: Download artifacts
  chroot: true
  script: ../debos/download-artifacts.sh

- action: recipe
  recipe: ../debos/ospack.yaml

- action: recipe
  recipe: ../debos/osvideopack.yaml
  multi_cam_rkaiq: "true"

- action: recipe
  recipe: ./osmodelpack.yaml

- action: recipe
  recipe: ../debos/image.yaml
  osinpack: "osmodelpack"
