# recipe.yaml

debosargs: ["--memory=4G"]

architecture: arm64

actions:
- action: recipe
  recipe: ../debos/ospack.yaml

- action: recipe
  recipe: ../debos/osvideopack.yaml
  multi_cam_rkaiq: "true"

- action: recipe
  recipe: ./osmodelpack.yaml

- action: recipe
  recipe: ../debos/image.yaml
  osinpack: "osmodelpack"
