name: Build and Release OpenAIA Debmodel 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debmodel 6TOPS runner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Remote Docker
      uses: docker/setup-buildx-action@v1

    - name: Set WORK_PATH
      run: |
        echo "WORK_PATH=$(dirname "${GITHUB_WORKSPACE}")" >> $GITHUB_ENV
        echo "WORK_PATH=${{ env.WORK_PATH }}"

    - name: Clone OpenAIA Debmodel
      run: |
        mkdir ${{ env.WORK_PATH }}/debmodel-openaia
        cp -rf ${{ env.WORK_PATH }}/debmodel ${{ env.WORK_PATH }}/debmodel-openaia
        cd ${{ env.WORK_PATH }}/debmodel-openaia
        git clone https://github.com/openaia/debos.git

    - name: Download artifacts
      run: |
        cd ${{ env.WORK_PATH }}/debmodel-openaia
        cd debos && ./download-artifacts.sh && cd -
        cd debmodel && ./download-artifacts.sh && cd -

    - name: Build OpenAIA Debmodel
      run: |
        cd ${{ env.WORK_PATH }}/debmodel-openaia
        docker run --rm --tty \
          --privileged \
          --net host \
          -v ${{ env.WORK_PATH }}/debmodel-openaia:/home/build/shared \
          -w /home/build/shared ghcr.io/openaia/easy-build/build-debos:bookworm-v0.1 \
          sudo debos --memory=4Gb -t imgname:6tops debmodel/recipe.yaml

    - name: Upload output artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v2023.12-6TOPS-rc1"
        body: |
          ## OpenAIA Debmodel v2023.11 Release
          - Add 6TOPS NCM support
          - Edgeble NCM6B, NCM6A
          - Fix for USB3.0 hang
        files: |
          ${{ env.WORK_PATH }}/debmodel-openaia/openaia-bullseye-6tops.bmap
          ${{ env.WORK_PATH }}/debmodel-openaia/openaia-bullseye-6tops.img.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
