name: Build and Release OpenAIA Debmodel 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debmodel 6TOPS runner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Remote Docker
      uses: docker/setup-buildx-action@v1

    - name: Authenticate Docker Registry
      run: |
        echo "Decoded Docker Auth Config:"
        decoded_config=$(echo -n "${{ secrets.DOCKER_AUTH_CONFIG }}" | base64 --decode)
        echo "$decoded_config" > $HOME/.docker/config.json
        cat $HOME/.docker/config.json

    - name: Set WORK_PATH
      run: |
        echo "WORK_PATH=$(dirname "${GITHUB_WORKSPACE}")" >> $GITHUB_ENV
        echo "WORK_PATH=${{ env.WORK_PATH }}"

    - name: Clone OpenAIA Debmodel
      run: |
        mkdir ${{ env.WORK_PATH }}/debmodel-openaia
        cp -rf ${{ env.WORK_PATH }}/debmodel ${{ env.WORK_PATH }}/debmodel-openaia
        cd ${{ env.WORK_PATH }}/debmodel-openaia
        git clone https://github.com/openaia/debos.git

    - name: Download artifacts
      run: |
        cd ${{ env.WORK_PATH }}/debmodel-openaia
        cd debos && ./download-artifacts.sh && cd -
        cd debmodel && ./download-artifacts.sh && cd -

    - name: Build OpenAIA Debmodel
      run: |
        sudo apt install qemu-user-static
        sudo apt install binfmt-support
        cd ${{ env.WORK_PATH }}/debmodel-openaia
        docker run --rm --tty \
          --privileged \
          --net host \
          -v ${{ env.WORK_PATH }}/debmodel-openaia:/home/build/shared \
          -v /dev:/dev \
          -e DEBIAN_FRONTEND=noninteractive \
          -e TERM=xterm-256color \
          -w /home/build/shared ghcr.io/edgeble/easy-dock/debian:bookworm-v1 \
          sudo debos --memory=8Gb -t imgname:6tops debmodel/recipe.yaml

    - name: Upload output artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v2024.02-rc1"
        body: |
          ## OpenAIA Debomodel v2024.02-rc1
          - Add WiFi firmware
          - Add RTL Ethernet firmware
          - Add BT firmware
          - Add linux-next support
          - Cleanup packages
          - Add new artifacts for linux-next
        files: |
          ${{ env.WORK_PATH }}/debmodel-openaia/ospack-bullseye-arm64.tar.gz
          ${{ env.WORK_PATH }}/debmodel-openaia/osvideopack-bullseye-arm64.tar.gz
          ${{ env.WORK_PATH }}/debmodel-openaia/osmodelpack-bullseye-arm64.tar.gz
          ${{ env.WORK_PATH }}/debmodel-openaia/openaia-bullseye-6tops.bmap
          ${{ env.WORK_PATH }}/debmodel-openaia/openaia-bullseye-6tops.img.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
